name: Grain CI Workflow

on: [push, pull_request]

jobs:
  build:
    name: Build and test on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}

  test-pkg:
    name: Test pkg binaries
    needs: [build]
    uses: ./.github/workflows/test-pkg.yml
